# Generated by Django 6.0.7 on 2026-07-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publication_year', models.PositiveIntegerField()),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('AR', 'Arabic'), ('OTHER', 'Other')], default='EN', max_length=10)),
                ('cover_url', models.URLField(blank=True)),
                ('shelf_location', models.CharField(blank=True, max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LOAN', 'On loan'), ('HELD', 'Held for reservation'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('ARCHIVED', 'Archived')], default='AVAILABLE', max_length=12)),
                ('shelf_location', models.CharField(blank=True, max_length=50)),
                ('acquired_at', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book')),
            ],
            options={
                'ordering': ['book', 'barcode'],
                'indexes': [models.Index(fields=['status'], name='catalog_boo_status_da6f38_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='catalog_boo_publica_83e549_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_archived'], name='catalog_boo_is_arch_ac9d09_idx'),
        ),
    ]
